# Generated by Django 2.2.7 on 2020-06-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
