# Generated by Django 2.2.7 on 2020-06-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APIs', '0002_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('published_at', models.DateField()),
                ('url_image', models.URLField()),
            ],
        ),
    ]
