# Generated by Django 2.2.7 on 2020-06-26 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0003_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
