# Generated by Django 2.2.7 on 2020-06-27 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0005_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='category',
        ),
    ]
