# Generated by Django 2.2.7 on 2020-06-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0006_auto_20200627_1041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
