# Generated by Django 2.2.7 on 2020-06-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0008_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
