# Generated by Django 2.2.7 on 2020-06-27 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0013_auto_20200627_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='publishedAt',
            new_name='published',
        ),
    ]
