# Generated by Django 2.2.7 on 2020-06-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0014_auto_20200628_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='urlToImage',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
