# Generated by Django 2.2.7 on 2020-06-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0015_auto_20200628_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_on_date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('published', models.DateField(blank=True, null=True)),
                ('urlToImage', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
