# Generated by Django 2.2.7 on 2020-06-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0016_news_on_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News_on_date',
        ),
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
